"""create runtimes table

Revision ID: 3fb3d0e7bce0
Revises: 
Create Date: 2026-05-25 19:50:47.629199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fb3d0e7bce0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runtimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('runtime_state', sa.String(length=50), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runtimes')
    # ### end Alembic commands ###
